services:
  - type: web
    name: mini-school-portal-2-0-backend
    env: node
    rootDir: backend
    buildCommand:  npm ci

    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false
      - key: JWT_ACCESS_SECRET
        sync: false
      - key: JWT_REFRESH_SECRET
        sync: false
      - key: ACCESS_TOKEN_EXPIRES_IN
        value: 15m
      - key: REFRESH_TOKEN_EXPIRES_IN
        value: 7d




  - type: static
    name: mini-school-portal-2-0-frontend
    env: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: ./dist
    envVars:
    - key: VITE_API_URL
      value: https://mini-school-portal-2-0-backend.onrender.com